on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  auto_ff:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git checkout main
          git merge --ff-only staging
          git push
