on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  auto_ff:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: |
        git checkout main
        git merge --ff-only staging
        git push
